# Generated by Django 4.2.1 on 2023-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("location", models.CharField(max_length=50)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("NON_IT", "NON_IT"),
                            ("phones", "phones"),
                        ],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
