# Generated by Django 4.2.1 on 2023-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("manager", "manager"),
                    ("Software_Dev", "Software Dev"),
                    ("Project Manager", "project manager"),
                ],
                max_length=50,
            ),
        ),
    ]
